project:
  type: website
  resources:
    - styles.css

website:
  title: "CAITG AI Winter School" 
  navbar:
    left:
      - href: session/01-intro.ipynb
        text: Python
      - text: "Tailoring LLMs"
        menu:
          - href: session/02-a-finetune.ipynb
            text: Finetuning
          - href: session/02-b-RAG.ipynb
            text: RAG
      - href: session/03-agents.ipynb
        text: Agents
      - href: session/04-a-cv.ipynb
        text: "Multimodal AI & Computer Vision"
      - text: "Bonus"
        menu:
          - href: session/99-a-antigravity.qmd
            text: Antigravity
          - href: session/99-b-ML.ipynb
            text: Machine Learning
          - href: session/99-cv-objectdetection_mediapipe.ipynb
            text: "MediaPipe object detection"
  google-analytics:
    tracking-id: "G-344M4P3CHH"
    storage: cookies
    anonymize-ip: true
  repo-url: https://github.com/gdgaiforscience/CAITG-WinterSchool
  repo-actions: [edit]

format:
  html:
    css: styles.css
    toc: true
    toc-depth: 2
    code-overflow: wrap
    respect-user-color-scheme: true
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom.scss]


